/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsys.frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static librarymanagementsys.util.DBAttributes.DUE_DATE;
import static librarymanagementsys.util.DBAttributes.ISSUE_BOOK_NAME;
import static librarymanagementsys.util.DBAttributes.ISSUE_DATE;
import static librarymanagementsys.util.DBAttributes.ISSUE_DB;
import static librarymanagementsys.util.DBAttributes.ISSUE_STATUS;
import static librarymanagementsys.util.DBAttributes.ISSUE_STUD_NAME;
import librarymanagementsys.util.DBConnection;

/**
 *
 * @author Ashutosh
 */
public class IssuedBooks extends javax.swing.JFrame {

    /**
     * Creates new form IssuedBooks
     */
    DefaultTableModel model;
    public IssuedBooks() {
        super("Issued Books");
        initComponents();
        fetchIssueDetails();
    }
    
    public void fetchIssueDetails() {
        
        try {
            Connection conn = DBConnection.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from " + ISSUE_DB + ";");
            while(rs.next()) {
                String Id = rs.getString("id");
                String studName = rs.getString(ISSUE_STUD_NAME);
                String bkName = rs.getString(ISSUE_BOOK_NAME);
                String issue1 = rs.getString(ISSUE_DATE);
                String due1 = rs.getString(DUE_DATE);
                String status = rs.getString(ISSUE_STATUS);
                
                // Create an object array
                Object[] obj = {Id, bkName, studName, issue1, due1, status}; 
                
                model = (DefaultTableModel) table_issue_details.getModel();
                // using this model we can add rows fetched from db
                model.addRow(obj);  // pass the object array
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Databse Connection Error");
            e.printStackTrace();
        }
    }
    
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) table_issue_details.getModel();
        model.setRowCount(0);
    }
    
    public void search() throws NullPointerException {
        Date issue = issuedt.getDatoFecha();
        Date due = duedt.getDatoFecha();
        long l1 = issue.getTime();
        long l2 = due.getTime();
        java.sql.Date issueDate = new java.sql.Date(l1);
        java.sql.Date dueDate = new java.sql.Date(l2);
        clearTable();
        try {
            Connection con = DBConnection.getConnection();
            String query = "select * from " + ISSUE_DB + " where " + ISSUE_DATE + " between ? and ?;";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setDate(1, issueDate);
            pst.setDate(2, dueDate);
            ResultSet rs = pst.executeQuery();
            if(!rs.next()) {
                JOptionPane.showMessageDialog(this, "No record found!!");
                return;
            }
            while(rs.next()) {
                String Id = rs.getString("id");
                String studName = rs.getString(ISSUE_STUD_NAME);
                String bkName = rs.getString(ISSUE_BOOK_NAME);
                String issue1 = rs.getString(ISSUE_DATE);
                String due1 = rs.getString(DUE_DATE);
                String status = rs.getString(ISSUE_STATUS);
                
                // Create an object array
                Object[] obj = {Id, bkName, studName, issue1, due1, status}; 
                
                model = (DefaultTableModel) table_issue_details.getModel();
                // using this model we can add rows fetched from db
                model.addRow(obj);  // pass the object array
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        duedt = new rojeru_san.componentes.RSDateChooser();
        issuedt = new rojeru_san.componentes.RSDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b2 = new rojerusan.RSMaterialButtonCircle();
        jPanel16 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_issue_details = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/books/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel10.setText("   Issued Books");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 330, 90));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 370, 5));

        duedt.setColorBackground(new java.awt.Color(255, 50, 149));
        duedt.setColorForeground(new java.awt.Color(255, 50, 149));
        duedt.setPlaceholder("Due Date");
        jPanel1.add(duedt, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 200, 350, 50));

        issuedt.setColorBackground(new java.awt.Color(255, 50, 149));
        issuedt.setColorForeground(new java.awt.Color(255, 50, 149));
        issuedt.setPlaceholder("Issue Date");
        jPanel1.add(issuedt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 350, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Issue Date :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 200, 140, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Due Date :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, -1, 50));

        b2.setBackground(new java.awt.Color(255, 133, 255));
        b2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b2.setText("Search");
        b2.setActionCommand("");
        b2.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b2MouseExited(evt);
            }
        });
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 180, 250, 80));

        jPanel16.setBackground(new java.awt.Color(255, 50, 149));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/books/icons8_Rewind_48px.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel16.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 70));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1850, 310));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_issue_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book Name", "Student", "Issued On", "Due Date", "Status"
            }
        ));
        table_issue_details.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        table_issue_details.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        table_issue_details.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        table_issue_details.setColorSelBackgound(new java.awt.Color(255, 50, 149));
        table_issue_details.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        table_issue_details.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        table_issue_details.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        table_issue_details.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        table_issue_details.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_issue_details.setRowHeight(40);
        table_issue_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_issue_detailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_issue_details);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 1520, 410));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1850, 670));

        setSize(new java.awt.Dimension(1868, 1027));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        try {
            search();
        } catch(NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Date fields can't be empty");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void table_issue_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_issue_detailsMouseClicked

    }//GEN-LAST:event_table_issue_detailsMouseClicked

    private void b2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseEntered
        b2.setBackground(new java.awt.Color(255,50,149));
    }//GEN-LAST:event_b2MouseEntered

    private void b2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseExited
        b2.setBackground(new java.awt.Color(255,133,255));
    }//GEN-LAST:event_b2MouseExited

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssuedBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle b2;
    private rojeru_san.componentes.RSDateChooser duedt;
    private rojeru_san.componentes.RSDateChooser issuedt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSTableMetro table_issue_details;
    // End of variables declaration//GEN-END:variables
}
