/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsys.frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static librarymanagementsys.util.DBAttributes.BOOK_DB;
import static librarymanagementsys.util.DBAttributes.BOOK_ID;
import static librarymanagementsys.util.DBAttributes.DUE_DATE;
import static librarymanagementsys.util.DBAttributes.ISSUE_BOOK_ID;
import static librarymanagementsys.util.DBAttributes.ISSUE_BOOK_NAME;
import static librarymanagementsys.util.DBAttributes.ISSUE_DATE;
import static librarymanagementsys.util.DBAttributes.ISSUE_DB;
import static librarymanagementsys.util.DBAttributes.ISSUE_STATUS;
import static librarymanagementsys.util.DBAttributes.ISSUE_STUD_ID;
import static librarymanagementsys.util.DBAttributes.ISSUE_STUD_NAME;
import librarymanagementsys.util.DBConnection;

/**
 *
 * @author Ashutosh
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        super("Return Books");
        initComponents();
    }
    
    private void getIssueDetails() {
        boolean b = false;
        int bkId = Integer.parseInt(txt_book_id.getText());
        int studId = Integer.parseInt(txt_stud_id.getText());
        try {
            Connection conn = DBConnection.getConnection();
            String query = "select * from " + ISSUE_DB + " where " + ISSUE_BOOK_ID + " = ? and " + ISSUE_STUD_ID + " = ? " + 
                    " and " + ISSUE_STATUS + " = ?;";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, bkId);
            pst.setInt(2, studId);
            pst.setString(3, "pending");
            ResultSet rs = pst.executeQuery();
            if(rs.next()) {
                b=true;
                lb1.setText(rs.getString("id"));
                lb2.setText(rs.getString(ISSUE_BOOK_NAME));
                lb3.setText(rs.getString(ISSUE_STUD_NAME));
                lb4.setText(rs.getString(ISSUE_DATE));
                lb5.setText(rs.getString(DUE_DATE));
            } else {
                lb9.setText("No Record Found!!");
                lb1.setText("");
                lb2.setText("");
                lb3.setText("");
                lb4.setText("");
                lb5.setText("");
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public boolean returnBook() {
        int rowsAffected = 0;
        int bkId = Integer.parseInt(txt_book_id.getText());
        int studId = Integer.parseInt(txt_stud_id.getText());
        try {
            Connection con = DBConnection.getConnection();
            String query = "Update " + ISSUE_DB + " set " + ISSUE_STATUS + " = ? where " + ISSUE_BOOK_ID + " = ? and " +
                    ISSUE_STUD_ID + " = ? and " + ISSUE_STATUS + " = ?;";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, "returned");
            pst.setInt(2, bkId);
            pst.setInt(3, studId);
            pst.setString(4, "pending");
            rowsAffected = pst.executeUpdate();
            
        } catch(SQLException e) {
            e.printStackTrace();
        }
        return rowsAffected > 0;
    }
    
    private void updateBookCount() {
        int rowsAffected = 0;
        int id = Integer.parseInt(txt_book_id.getText());
        try {
            Connection conn = DBConnection.getConnection();
            String query = "update " + BOOK_DB + " set quantity=quantity+1 where " + BOOK_ID + " = ?;";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            rowsAffected = pst.executeUpdate();
        } catch(Exception e) {
            e.printStackTrace();
        }
        if(rowsAffected > 0) {
            int qty = Integer.parseInt(lb5.getText());
            lb5.setText(Integer.toString(qty-1));
        } else JOptionPane.showMessageDialog(this, "Error Occurred");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        b2 = new rojerusan.RSMaterialButtonCircle();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lb3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        txt_book_id = new javax.swing.JTextField();
        txt_stud_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        b3 = new rojerusan.RSMaterialButtonCircle();
        jLabel2 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b2.setBackground(new java.awt.Color(255, 50, 149));
        b2.setText("Return Book");
        b2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel7.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 810, 350, 90));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 50, 149));
        jLabel31.setText("Book ID :");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 280, 120, 50));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 50, 149));
        jLabel32.setText("Student ID :");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 420, 160, 50));

        jPanel4.setBackground(new java.awt.Color(255, 50, 149));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/books/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel10.setText("   Book Details");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 280, 120));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 370, 5));

        lb3.setBackground(new java.awt.Color(255, 255, 255));
        lb3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 300, 50));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Student Name :");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 150, 50));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Issue Date :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 120, 50));

        lb9.setBackground(new java.awt.Color(255, 255, 255));
        lb9.setFont(new java.awt.Font("Yu Gothic Medium", 1, 20)); // NOI18N
        lb9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(lb9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 900, 300, 50));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Issue ID :");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 90, 50));

        lb1.setBackground(new java.awt.Color(255, 255, 255));
        lb1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 300, 50));

        lb5.setBackground(new java.awt.Color(255, 255, 255));
        lb5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 780, 300, 50));

        lb2.setBackground(new java.awt.Color(255, 255, 255));
        lb2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 300, 50));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Due Date :");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 110, 50));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Book Name :");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 120, 50));

        lb4.setBackground(new java.awt.Color(255, 255, 255));
        lb4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 680, 300, 50));

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 530, 980));

        txt_book_id.setBackground(new java.awt.Color(204, 204, 204));
        txt_book_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_book_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_book_id.setToolTipText("");
        txt_book_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 50, 149)));
        txt_book_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_book_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_book_idFocusLost(evt);
            }
        });
        txt_book_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_book_idActionPerformed(evt);
            }
        });
        jPanel7.add(txt_book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 280, 350, 50));

        txt_stud_id.setBackground(new java.awt.Color(204, 204, 204));
        txt_stud_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_stud_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_stud_id.setToolTipText("");
        txt_stud_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 50, 149)));
        txt_stud_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_stud_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_stud_idFocusLost(evt);
            }
        });
        txt_stud_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stud_idActionPerformed(evt);
            }
        });
        jPanel7.add(txt_stud_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 410, 350, 50));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 50, 149));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/books/icons8_Books_52px_1.png"))); // NOI18N
        jLabel1.setText(" Return Book");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 50, 330, 120));

        jPanel6.setBackground(new java.awt.Color(255, 50, 149));
        jPanel6.setForeground(new java.awt.Color(255, 50, 149));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1345, 150, 380, 5));

        b3.setBackground(new java.awt.Color(102, 102, 255));
        b3.setText("Find Book");
        b3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel7.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 660, 350, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 980));

        jPanel17.setBackground(new java.awt.Color(102, 102, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/books/icons8_Rewind_48px.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel17.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jPanel7.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1850, 980));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1850, 980));

        setSize(new java.awt.Dimension(1868, 1027));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void txt_stud_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stud_idActionPerformed

    }//GEN-LAST:event_txt_stud_idActionPerformed

    private void txt_book_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_book_idActionPerformed

    }//GEN-LAST:event_txt_book_idActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(!txt_book_id.getText().equals("") && !txt_stud_id.getText().equals("")) {
            if(returnBook()) {
                JOptionPane.showMessageDialog(this, "Book Returned");
                updateBookCount();
            } else JOptionPane.showMessageDialog(this, "Book return failed");
        }
        else JOptionPane.showMessageDialog(this, "All Fields are required");
    }//GEN-LAST:event_b2ActionPerformed

    private void txt_book_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_book_idFocusLost
        
    }//GEN-LAST:event_txt_book_idFocusLost

    private void txt_stud_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_stud_idFocusLost
        
    }//GEN-LAST:event_txt_stud_idFocusLost

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(!txt_book_id.getText().equals("") && !txt_stud_id.getText().equals("")) getIssueDetails();
        else JOptionPane.showMessageDialog(this, "All Fields are required");
    }//GEN-LAST:event_b3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle b2;
    private rojerusan.RSMaterialButtonCircle b3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb9;
    private javax.swing.JTextField txt_book_id;
    private javax.swing.JTextField txt_stud_id;
    // End of variables declaration//GEN-END:variables
}
