/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsys.frames;

import librarymanagementsys.frames.Login;
import librarymanagementsys.util.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashutosh
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        super("Sign-Up");
        initComponents();
    }
    
    // check for duplicacy
    private boolean verifyIntegrity(String name, String email) {
        boolean exists = false;
        Connection conn = DBConnection.getConnection();
        try {
            PreparedStatement pst = conn.prepareStatement("Select * from users where name = ? and email = ?");
            pst.setString(1, name);     // value for first place holder
            pst.setString(2, email);    // value for second place holder
            ResultSet rs = pst.executeQuery();
            if(rs.next()) exists = true;
        }catch(SQLException e) {
            e.printStackTrace();
        }
        return exists;
    }
    
    // insert signup data into database table
    public void insertSignUpDetails() {
        String name = signup_username_field.getText();
        String pass = signup_pwd_field.getText();
        String email = signup_email_field.getText();
        if (!verifyIntegrity(name, email)) {
            try {
                if (name.equals("")) {
                    JOptionPane.showMessageDialog(this, "Username can't be NULL");
                    throw new RuntimeException("USERNAME NULL");
                } else if (pass.equals("")) {
                    JOptionPane.showMessageDialog(this, "Password can't be NULL");
                    throw new RuntimeException("PASSWORD NULL");
                } else if (email.equals("")) {
                    email = "NULL";
                }

                Connection conn = DBConnection.getConnection();
                String query = "insert into users(name, password, email) values(?,?,?)";
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1, name);
                pst.setString(2, pass);
                pst.setString(3, email);
                int rows_affected = pst.executeUpdate();
                if (rows_affected > 0) {
                    JOptionPane.showMessageDialog(this, "User Registration Successful");
                    new Login().setVisible(true);
                    this.dispose();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }else {
            JOptionPane.showMessageDialog(this, "User already exists!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signup_username_field = new javax.swing.JTextField();
        signup_email_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        signup_pwd_field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        signup_signup_btn = new rojerusan.RSMaterialButtonCircle();
        b1 = new rojerusan.RSMaterialButtonCircle();
        jLabel11 = new javax.swing.JLabel();

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(0, 86, 255));
        rSMaterialButtonCircle1.setText("SIGN UP");
        rSMaterialButtonCircle1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 86, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LIBRARY MANAGEMENT SYSTEM");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 610, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/signup-icon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 950, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 900));

        jPanel2.setBackground(new java.awt.Color(181, 74, 240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("X");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 40, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Here? Sign-Up to Continue");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 90, 40));

        signup_username_field.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        signup_username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_username_fieldActionPerformed(evt);
            }
        });
        jPanel2.add(signup_username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 340, 50));

        signup_email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_email_fieldActionPerformed(evt);
            }
        });
        jPanel2.add(signup_email_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 340, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secured_Letter_50px.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 50, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 60, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 90, 40));

        signup_pwd_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_pwd_fieldActionPerformed(evt);
            }
        });
        jPanel2.add(signup_pwd_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 340, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 60, 70));

        signup_signup_btn.setBackground(new java.awt.Color(181, 0, 167));
        signup_signup_btn.setText("SIGN UP");
        signup_signup_btn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        signup_signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_signup_btnActionPerformed(evt);
            }
        });
        jPanel2.add(signup_signup_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 780, 250, 80));

        b1.setBackground(new java.awt.Color(0, 86, 255));
        b1.setText("LOG IN");
        b1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel2.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, 250, 80));

        jLabel11.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("WELCOME USER");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 570, 910));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signup_email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_email_fieldActionPerformed

    private void signup_pwd_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_pwd_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_pwd_fieldActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b1ActionPerformed

    private void signup_signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_signup_btnActionPerformed
        insertSignUpDetails();
    }//GEN-LAST:event_signup_signup_btnActionPerformed

    private void signup_username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_username_fieldActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle b1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private javax.swing.JTextField signup_email_field;
    private javax.swing.JTextField signup_pwd_field;
    private rojerusan.RSMaterialButtonCircle signup_signup_btn;
    private javax.swing.JTextField signup_username_field;
    // End of variables declaration//GEN-END:variables
}
